language: ruby

rvm:
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

branches:
  only:
    - develop

sudo: false

cache: bundler

script:
  - JEKYLL_ENV=production bundle exec jekyll build

env:
  global:
    secure: hKmM3bY7wTssgBjKzNz2kXahI4xTugfCjRN+ulFpCEa1qJBW5EWMvd0uTkG72emzoG7A4GbMIVPlEC5gstDAOlrYLMb1iFmhehlm+0Lf0nLIFIooqVch+BaEtwK29MFgw3Ww94/Cl1NxlQC6BFTBAobSYX8gLuKHC5I046De5/swB5lQNxVib36myRfDmw+Hkciz5eM6DqKXntn5UjtSYcPqkqz+7pnG3d6eDH1jx5sxPjYSm9ETSgGJ9ky2iNWt2eBHd9/1xn8h6IUqJWAZW7dSyPPmyI+a8mcXK/7bRFrJAf511XGLnazWxdbPLJxorJnKXbrJDuKwrlqg5SD3O8Jc9meW3gQCJQVJdtsM7FKoOBeW4hVoHRzFWbk+c9Cruf6hONihu+N9UBs6PnJYULYPkKPtLB0yEiKwWfymN6P3YyGXY79ktKwFM7/mzHTyRNDkfSEF50XbXS5G0J52OaHOznD4+Zfd7lZJuQmEdHuBsFiX6wPBLoW/4GEHx5+1ZQ5uwVYT+jumOH7N3yLztUBNN9AgAAfekoOXCIh2ds6Vg8eLA3SX6UCSwiLmtHptD53QJHkxqOPIgltVxbfHEWEcAg1KOJ6sGyQ9/9Me+KtDB03npIhKmfCzzE8ZWJARlKrjAyUY4hDZ7trnpGOz4hGEFEEP6QW1+Lq7YvB55E8=

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  name: Travis CI
  email: travis-ci@daveherbert.co.uk
  keep_history: true
  local_dir: _site
  target_branch: master
  on:
    branch: develop
