language: ruby

rvm:
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

branches:
  only:
    - develop

sudo: false

cache: bundler

script:
  - JEKYLL_ENV=production bundle exec jekyll build

